1password
alfred
calibre
couleurs
discord
docker
dropbox
font-fontawesome
font-awesome-terminal-fonts
font-hack
font-inconsolata-dz-for-powerline
font-inconsolata-g-for-powerline
font-inconsolata-for-powerline
font-roboto-mono
font-roboto-mono-for-powerline
font-source-code-pro
google-chrome
gpg-suite
insomnia
istat-menus
iterm2-beta
licecap
little-snitch
spectacle
spotify
the-unarchiver
transmit
transmission
visual-studio-code
vlc
