GITPROJECT: GITPROJECT    # name of YOUR dotfiles project
GITUSER: GITHUBUSER       # name of YOUR github user
LASTNAME: LASTNAME        # YOUR lastname
FIRSTNAME: FIRSTNAME      # YOUR firstname
EMAIL: EMAIL              # YOUR email address
GITDIR: GITDIR            # path to where you usually clone your git project
HOSTNAME: HOSTNAME        # desired hostname for the mMac
KEEPSUDO: "false"         # keep or not passwordless sudo after the install - false = remove, everything else = keep
